### ISSUE TITLE
Selecting element from autosuggestion IE

### ISSUE THREAD

**Issue by MitaliDhamale** [ZEISS/precise-ui#123]
**Description:**
Selecting an element from autosuggestion do not close the suggestions.

**Steps to reproduce:**

// todo

**Expected behavior:**
The autosuggestion should be closed once the user selects an element from autosuggestion

**Actual behavior:**
The selected element is still displayed as a suggestion to the user in IE

**Environment Details:**
 IE11

**Comment by dimabory** [comment]
@MitaliDhamale Can you use the default template for bug's description https://github.com/ZEISS/precise-ui/blob/master/.github/ISSUE_TEMPLATE/bugs.md?
