### ISSUE TITLE
Two cross buttons displayed inside 'Search'

### ISSUE THREAD

**Issue by MitaliDhamale** [ZEISS/precise-ui#124]
**Description**
Two cross button displayed inside search textbox as user start searching for any term. (IE11)
 
**Steps to reproduce:**

// todo

**Expected behavior:**
Only one cross button displayed in search box

**Actual behavior:**
Two cross buttons displayed in the search box.

**Environmental Details:**
IE11

**Comment by dimabory** [comment]
@MitaliDhamale the same here https://github.com/ZEISS/precise-ui/issues/123#issuecomment-511879135
