### ISSUE TITLE
Support grouping of items with no value for the 'groupBy' column in AccordionTable

### ISSUE THREAD

**Issue by lestard** [ZEISS/precise-ui#126]
### Description

When some of the items in a `AccordionTable` don't have a value for the column that the table is grouped by, the behaviour is not consistent and not very convinient. 

If an item without a value is the first in the data list, then the grouping of items doesn't work correctly at all. In this case items without a value are mixed in between grouped items. In this case it can look like some items without a value are included in one of the groups which is not correct. The source for this problems is in the sorting algorithm that is deciding on how to sort items based on the type of value of the first item in the list.

My proposal includes:
- fix the sorting by not looking at the first item in the list but search for the first item that actually has a value set for the `sortby`/`groupBy` column
- change the order of items so that items without a value are moved to the end of the list
- add a pseudo-group for all items that don't have a value for the `groupBy` field so that you can toggle this group like normal groups.
- Add a prop to `AccordionTable` to define a label value that should be used for this group of items without a value. This prop should be optional. If no value was defined then use something like "-" as a default

**Comment by guiherzog** [comment]
This has been added in the latest commits. Thanks @lestard for the fix.
