### ISSUE TITLE
Checkbox Formate in IE

### ISSUE THREAD

**Issue by ZOFLLUTZ** [ZEISS/precise-ui#131]
**Description:**
The Checkbox component looks strange in IE11

**Steps to reproduce:**

Verify Checkbox in IE

**Expected behavior:**
Looks the same as in https://precise-ui.io/#/Components/CheckboxInt

**Actual behavior:**
Check in the Screenshots

Environment:
IE11
![Screenshot2](https://user-images.githubusercontent.com/53431152/62043414-94efd300-b200-11e9-920e-8cfe3f6b1956.jpg)
![Screenshot3](https://user-images.githubusercontent.com/53431152/62043415-94efd300-b200-11e9-865d-9167db85092a.jpg)

**Comment by ZOFLLUTZ** [comment]
@dimabory @kotielnikov

**Comment by dimabory** [comment]
@kotielnikov I'm able to fix this issue, but checkbox size will be changed from `17x17` to `21x21` upon changing `box-sizing` property. This change seems like BC, so the main question "is it okay to fix it by this way?"

**Comment by dimabory** [comment]
Found workarounds! https://github.com/philipwalton/flexbugs/issues/3
