### ISSUE TITLE
UploaderProgressDetails of FileUploaderDetails opens behind first Modal

### ISSUE THREAD

**Issue by rad3k1** [ZEISS/precise-ui#145]
### Description
If FileUploader with FileUploaderDetails is called from antoher Modal, the UploaderProgressDetails of FileUploaderDetails opens behind that modal.

![UploaderProgressDetails2](https://user-images.githubusercontent.com/53941899/62850037-0724e500-bce2-11e9-982f-2d8c756643ef.png)

UploaderProgressDetails should appear in fornt of that modal, just like UploaderProgressBar.
To solve this issue the "z-index" of UploaderProgressDetails should be set to "10001" (just like in case of UploaderProgressBar).

**Comment by guiherzog** [comment]
This has been fixed in the latest 0.7.0 release. Thanks @rad3k1 for working on this :)
