### ISSUE TITLE
Single Email id not accepted in a field where user is allowed to enter multiple Email id's

### ISSUE THREAD

**Issue by MitaliDhamale** [ZEISS/precise-ui#163]
**Description:**
Single Email id is not excepted in a field , where user is allowed to enter multiple Email id's.
User has to mandatorily insert a comma(,) after an email id in order to submit the form.

**Pre-requisites**
1. Email field can accept multiple email id (comma separated)

**Steps to reproduce:**
1. Enter valid Email id
2. Try to save the form

**Expected behavior:**
Single email id should be accepted without a comma ( , )

**Actual behavior:**
Single Email id not accepted unless and until comma is provided at the end

**Environment:**
any OS/browser

**Possible Solution:**
To be clarified..

**Comment by jotdl** [comment]
This happened with the TagBuilder component. If you don't press the ⏎ or , key, the last element/tag you enter won't be added to the value of this component.

As it's kind of hidden to the user if it's a TagBuilder or TextField component (styling is very similar), the user won't know if he has to press ⏎/, or not. Once he submits the form without pressing those key within that field his last input get's lost.

Is there an option to trigger the finish of a Tag within the Component upon form submission?

**Comment by FlorianRappl** [comment]
> Is there an option to trigger the finish of a Tag within the Component upon form submission?

My opinion here is that the last piece of the `TagBuilder` input should *always* be considered an element (that is still in "edit" mode; but that does not take away its status as being a valid element or "tag").

I guess that requires some internal rework of the component, but it would be the most natural behavior and comply with the implementation of similar components on other websites.

**Comment by dimabory** [comment]
I have got an idea to add the new directive into `TagBuilder` to turn on(off) auto submitting the edited tag on `onBlur` event. It can look something like this:
```tsx
<TagBuilder appendTagOnBlur/>
```

**Comment by dimabory** [comment]
@FlorianRappl @jotdl are you ok with it?
