### ISSUE TITLE
Dropdown menu options truncated for longer text.

### ISSUE THREAD

**Issue by MitaliDhamale** [ZEISS/precise-ui#169]
**Description:**
The text is not visible completely in the dropdown menu, if the text to be selected is too long **IE11**

**Steps to reproduce:**
1. Try to select the option from the drop down which has larger text.

**Expected behavior:**
The option selected from the drop down should be visible(the complete text should be visible)

**Actual behavior:**
The option selected is not visible completely and seems distorted.

**Environment Details:**
IE11

**https://precise-ui.io/#/Components/DropdownSelect**

![DropdownOption](https://user-images.githubusercontent.com/52967194/63843758-36488100-c987-11e9-9e67-eef677add15a.png)

**Comment by dimabory** [comment]
Reopening due to #212 https://github.com/ZEISS/precise-ui/pull/212
