### ISSUE TITLE
Unable to select today's date in date field component

### ISSUE THREAD

**Issue by MitaliDhamale** [ZEISS/precise-ui#170]
**Description:**
User is unable to select today's date once he/she has selected Future dates from the date field component.

**Steps to reproduce:**

**Note:** Only happening if a default Date is set as of today's date.

**Expected behavior:**
User should be able to select today's date.

**Actual behavior:**
Todays date is not selectable.

**Environment Details:**
All browsers

![date Picker](https://user-images.githubusercontent.com/52967194/64410909-55809600-d08c-11e9-84da-7cecd8517a9c.png)

https://precise-ui.io/#/Components/DateField

**Comment by IKolosynskyi** [comment]
The issue has been fixed #180
