### ISSUE TITLE
Add onBeforeClose event to the Modal

### ISSUE THREAD

**Issue by gerkirill** [ZEISS/precise-ui#182]
### Description

The idea is to have onBeforeClose event in a modal. The event handler should be able to decide if the modal is allowed to close or not. It would be nice to have async. event handlers supported (ones returning Promise).

### Background

There is already an onClose event, but the corresponding handler is executed too late - when the modal closing animation has finished. The idea is to keep the backward compatibility, by leaving onClose event as is, but add a new one - onBeforeClose.

The possible use case is the following: the user fills in the form in a modal and then closes the modal, either by clicking "x" button or e.g. by accidentally clicking outside of the modal. We could use onBeforeClose event to display a confirmation dialog saying "Are you sure? All unsaved data will be lost."

Also can be useful for #152

**Comment by ZEISSLaurinAgostini** [comment]
The issue can be closed
