### ISSUE TITLE
DropdownMenu list has no width when expanded thus it's not possible to see the options on IE11

### ISSUE THREAD

**Issue by bajcmartinez** [ZEISS/precise-ui#201]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository?
- [X] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Versions

0.8.2-pre.593 and up

### Description

When using DropdownMenu on IE11, after clicking on the menu to see the list of options the list appears with 0 width, which makes it impossible to visualize or select any option

### Steps to Reproduce

1. Render a DropdownMenu component
2. Open the page with IE11
3. Expand the menu
4. See the result

**Expected behavior:** [What you expected to happen]

To see the list and be able to select any of the options

**Actual behavior:** [What actually happened]

![MicrosoftTeams-image](https://user-images.githubusercontent.com/23080979/68574095-6c1ae300-0469-11ea-8af1-34fe39d53828.png)

**Environment details:** [OS, Browser, ...]

IE11

### Possible Solution
The issue was introduced in commit e47590ae14162eecaf0361f6d7ea1215d7843470 particularly in `ListItemContent` change from

```
const ListItemContent = styled.div`
  flex-grow: 1;
`;
```

to

```
const ListItemContent = styled.div`
 flex-grow: 1;
 flex: 1 0 0px;
`;r
```

The change adding flex-basis to 0px broke the IE11 compatibility.

**Comment by dimabory** [comment]
I would say this commit is more precise 🙂 https://github.com/ZEISS/precise-ui/commit/6feff6c40b89dbee034f3f67d7ffac5c38aa0968
