### ISSUE TITLE
Pagination: negative page item/page numbers on empty content

### ISSUE THREAD

**Issue by ZEISSLaurinAgostini** [ZEISS/precise-ui#31]
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository?
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Versions

0.5.0

### Description

When changing the **items per page** on empty content, the item range will jump to negative numbers and you can select negative page numbers.

### Steps to Reproduce

1. Create a Pagination component without content (e.g. empty array) and more than one **items per page** size available
```
const { Pagination } = require('precise-ui');
const data = Array();

<Pagination size={[20, 50, 100]}>
  {data}
</Pagination>
```

2. Change the **items per page**

**Expected behavior:** Nothing should happen

**Actual behavior:** The items range will jump to a negative number (e.g. -49 - 0 of 0) and you can go to a previous (negative) page with the arrow button

**Environment details:** Windows 10, Google Chrome 

### Possible Solution

Line 131 in src/components/Pagination/index.tsx:
`const maxPageCount = Math.ceil(total / size) - 1;`
causes this issue, because for **total** == 0, the **maxPageCount** will be -1.

I already fixed and tested this and added more checks for this issue on other positions.

PR will come.

**Comment by FlorianRappl** [comment]
Cool thanks for contributing! <3

Would

```ts
const maxPageCount = Math.max(Math.ceil(total / size) - 1, 0);
```

solve this? I think this should be robust enough, or can you think of any other edge case?
