### ISSUE TITLE
Compatibility with Emotion

### ISSUE THREAD

**Issue by elektronik2k5** [ZEISS/precise-ui#96]
### Description

Can we add a build which depends on Emotion, in addition to the current, styled-components based one?

### Background

[Emotion](https://emotion.sh) is pretty popular, thanks to it's smaller bundle size and source maps support. It shares the same exact component API with styled and the changes should be minimal.

[SmoothUI](https://smooth-ui.smooth-code.com/) is an example of a component library which supports both styled and Emotion.

**Comment by FlorianRappl** [comment]
Sounds like a great proposal to me! Thanks for the examples @elektronik2k5 

Anyone? @kotielnikov @boromo

**Comment by boromo** [comment]
If they have the same API, why not, I would say that this could be a really nice feature to the library.

**Comment by elektronik2k5** [comment]
Alright, looks like I underestimated the level of complexity here. While the most common APIs are the same, the rest differ enough to not make it trivial.

I tried hacking `src/utils/styled.ts` to switch from styled's monolithic build to Emotion's modular packages: 
`'@emotion/styled'`, `'@emotion/core'`, `'emotion-theming'` but failed cause the types are real complex there and can't simply be swapped on a 1:1 basis between styled and emotion. :sweat: 

Pinging Emotion maintainers @Andarist @probablyup @mitchellhamilton @Ailrun @aaronjensen in hopes they'll be kind enough to help us here :angel:

**Comment by Andarist** [comment]
Well, it's really hard to give any advice without knowing which features from styled-components do you use. If they are used solely internally or externally too. Also what would be the goal - would you like to have as much common code between those 2 variants as possible or do you just want to have 2 completely separate builds?

**Comment by elektronik2k5** [comment]
@Andarist, thanks for responding! :bowing_man:  The goal is to make precise-ui work with Emotion and the means is whichever way would be easiest to implement initially and maintain further down the road.

**Comment by Andarist** [comment]
So looking really quickly through the repository I think it would be easiest to just make a sibling file to `styled.ts` (i.e. `styled.emotion.ts`) & alias all imports to original one to the emotion-variant. This might not play nicely with existing TS infra though - you'd have to explore how to make it work within that setup.

**Comment by kotielnikov** [comment]
in plans is to remove styled.ts, while it was used for assigning theme to all styled functions. Now there is a [different better mechanism](Stephan
About 9 hours ago
weframe AG) and the code will be updated accordingly soon.

Regarding usage of emotion - this will be possible only in the case of total compatibility with styled-components API and types. I personally against it because it will increase maintaining cost twice and there will be never total compatibility.
